# https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/

credentials:
  usernames:
    mrdn:
      email: code_cortex_2025@gmail.com
      name: Code Cortex
      city: Surat
      area: Surat Gujarat
      role: Admin
      password: '$2b$12$ByZbwxrcvCXVLQO4zjI95OteXToaBiwWDqujsHiKfeGzionz0VqAG' # abc
cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - code_cortex_2025@gmail.com